#include <stdbool.h>
#include <stdio.h>
#include "object.h"
#include "toggle.h"
static const char *tags0[] = { "east", "west", "north", "south", NULL};
static const char *tags1[] = { "tunnel", "mouth", "entrance", "beginning", NULL};
static const char *tags2[] = { "tunnel", "passage", "north", "south", NULL};
static const char *tags3[] = { "tunnel", "passage", "north", "south", "glimmer", NULL};
static const char *tags4[] = { "tunnel", "passage", "north", "south", "lake", NULL};
static const char *tags5[] = { "lake", "underground lake", "water", NULL};
static const char *tags6[] = { "island", "rock island", "lake island", "rock", NULL};
static const char *tags7[] = { "riddle rock", "rock", "polished rock", "riddle", "stone", NULL};
static const char *tags8[] = { "tunnel", "exit", "escape", "escape route", NULL};
static const char *tags9[] = { "token", NULL};
static const char *tags10[] = { "ring", "gold ring", "gold", "precious", "my precious", "shiny", NULL};
static bool condition11(void) { return thering->location == player && riddleSolvedToken->location != player; }
static const char *tags11[] = { "gollum", "creature", "riddle master", "monster", NULL};
static const char *tags12[] = { "yourself", "bilbo", "hobbit", NULL};
static const char *tags13[] = { "sting", "sword", "blade", "light", "glow", NULL};
static const char *tags14[] = { "sting", "sword", "blade", "light", "glow", NULL};
static const char *tags15[] = { "north", "tunnel", "passage", NULL};
static const char *tags16[] = { "south", "tunnel", "passage", NULL};
static bool condition17(void) { return lampOn->location == player; }
static const char *tags17[] = { "north", "tunnel", "passage", NULL};
static bool condition18(void) { return lampOn->location != player; }
static const char *tags18[] = { "north", "tunnel", "passage", NULL};
static const char *tags19[] = { "south", "tunnel", "passage", NULL};
static bool condition20(void) { return lampOn->location == player; }
static const char *tags20[] = { "north", "tunnel", "passage", "lake", NULL};
static bool condition21(void) { return lampOn->location != player; }
static const char *tags21[] = { "north", "tunnel", "passage", "lake", NULL};
static const char *tags22[] = { "south", "tunnel", "passage", NULL};
static bool condition23(void) { return lampOn->location == player; }
static const char *tags23[] = { "north", "tunnel", "passage", "lake", NULL};
static bool condition24(void) { return lampOn->location != player; }
static const char *tags24[] = { "north", "tunnel", "passage", "lake", NULL};
static const char *tags25[] = { "south", "tunnel", "passage", NULL};
static const char *tags26[] = { "east", "island", "rock", "stone", NULL};
static const char *tags27[] = { "west", "lake", "shore", NULL};
static const char *tags28[] = { "east", "rock", "riddle rock", "riddle", NULL};
static bool condition29(void) { return thering->location != player || riddleSolvedToken->location == player; }
static const char *tags29[] = { "west", "island", "back", NULL};
static bool condition30(void) { return thering->location == player && riddleSolvedToken->location != player; }
static const char *tags30[] = { "west", "island", "back", NULL};
static bool condition31(void) { return riddleSolvedToken->location == player; }
static const char *tags31[] = { "east", "tunnel", "escape", "exit", NULL};
static bool condition32(void) { return riddleSolvedToken->location != player; }
static const char *tags32[] = { "east", "tunnel", "escape", "exit", NULL};
static const char *tags33[] = { "unused", "door", NULL};
static const char *tags34[] = { "unused", "door", NULL};
static const char *tags35[] = { "unused", "door", NULL};
static const char *tags36[] = { "unused", "door", NULL};
static const char *tags37[] = { "unused", "box", NULL};
static const char *tags38[] = { "unused", "box", NULL};
static const char *tags39[] = { "unused", "box", NULL};
static const char *tags40[] = { "unused", "key", NULL};

static bool alwaysTrue(void) { return true; }

OBJECT objs[] = {
	{	/* 0 = gossipEWNS */
		alwaysTrue,
		NULL,
		tags0,
		NULL,
		NULL,
		NULL,
		"You see nothing special.",
		"You see",
		"You can't get much closer than this.",
		"It's just a compass direction.",
		99,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 1 = tunnel1 */
		alwaysTrue,
		"the mouth of a dark tunnel",
		tags1,
		NULL,
		NULL,
		NULL,
		"A cramped stone passage bends into the roots of the Misty Mountains. Something glints nearby.",
		"You see",
		"You can't get much closer than this.",
		"The mountain swallows all light.",
		99,
		9999,
		0,
		20,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 2 = tunnel2 */
		alwaysTrue,
		"a black tunnel running north and south",
		tags2,
		NULL,
		NULL,
		NULL,
		"Cold stone presses in on both sides. Without light, the way ahead is impossible to judge.",
		"You see",
		"You can't get much closer than this.",
		"I will need Sting's light to go deeper.",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 3 = tunnel3 */
		alwaysTrue,
		"a narrow tunnel with something glimmering in the dark",
		tags3,
		NULL,
		NULL,
		NULL,
		"The air is clammy and still. In the darkness, something small and golden lies on the ground.",
		"You see",
		"You can't get much closer than this.",
		"Something precious is here.",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 4 = laketunnel */
		alwaysTrue,
		"a tunnel sloping toward water",
		tags4,
		NULL,
		NULL,
		NULL,
		"The tunnel slopes downward. You hear the faint slap of water ahead.",
		"You see",
		"You can't get much closer than this.",
		"The air smells wet and ancient.",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 5 = undergroundLake */
		alwaysTrue,
		"an underground lake",
		tags5,
		NULL,
		NULL,
		NULL,
		"Black water laps quietly against the stone. The darkness over the lake feels alive.",
		"You see",
		"You can't get much closer than this.",
		"Something lives on the water.",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 6 = gollumsisland */
		alwaysTrue,
		"a low island in the middle of the lake",
		tags6,
		NULL,
		NULL,
		NULL,
		"A slick island of stone rises from the black lake. Bones and scraps lie scattered here.",
		"You see",
		"You can't get much closer than this.",
		"Someone has lived here for a very long time.",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 7 = riddlerock */
		alwaysTrue,
		"the riddle rock",
		tags7,
		NULL,
		NULL,
		NULL,
		"A broad polished stone sits like a crude throne. This is plainly where Gollum plays his game.",
		"You see",
		"You can't get much closer than this.",
		"A court for riddles and bargains.",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 8 = escapetunnel */
		alwaysTrue,
		"the tunnel leading out of the mountain",
		tags8,
		NULL,
		NULL,
		NULL,
		"A long cleft in the rock carries a faint breath of fresh air from the outside world.",
		"You see",
		"You can't get much closer than this.",
		"Freedom lies that way.",
		99,
		9999,
		0,
		100,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 9 = riddleSolvedToken */
		alwaysTrue,
		"a hidden token",
		tags9,
		NULL,
		NULL,
		NULL,
		"This object should never be seen.",
		"You see",
		"You can't get much closer than this.",
		"Hidden.",
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 10 = thering */
		alwaysTrue,
		"a gold ring",
		tags10,
		tunnel3,
		NULL,
		NULL,
		"A plain golden ring. It looks harmless, but it draws the eye at once.",
		"You see",
		"You can't get much closer than this.",
		"It feels strangely important.",
		1,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 11 = gollum */
		condition11,
		"Gollum",
		tags11,
		riddlerock,
		NULL,
		NULL,
		"A pale, wiry creature crouches on the stone, watching with hungry eyes.",
		"He has",
		"You can't get much closer than this.",
		"If I want to leave, I must beat him at his own game.",
		99,
		20,
		100,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 12 = player */
		alwaysTrue,
		"yourself",
		tags12,
		tunnel1,
		NULL,
		NULL,
		"A bewildered hobbit far beneath the Misty Mountains.",
		"You have",
		"You can't get much closer than this.",
		"Going on an adventure, they said.",
		99,
		20,
		100,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 13 = lampOff */
		alwaysTrue,
		"Sting",
		tags13,
		tunnel1,
		NULL,
		NULL,
		"An Elvish blade. In the darkness of the tunnels, it can be used as your light.",
		"You see",
		"You can't get much closer than this.",
		"If I draw Sting, I can see.",
		1,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 14 = lampOn */
		alwaysTrue,
		"Sting",
		tags14,
		NULL,
		NULL,
		NULL,
		"Sting is drawn and shining with a cold blue light.",
		"You see",
		"You can't get much closer than this.",
		"Now I can see through the dark tunnels.",
		1,
		0,
		0,
		100,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 15 = northFromTunnel1 */
		alwaysTrue,
		"a tunnel leading north",
		tags15,
		tunnel1,
		tunnel2,
		tunnel2,
		"The tunnel continues north into darkness.",
		"You see",
		"You move north into the tunnel.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 16 = southFromTunnel2 */
		alwaysTrue,
		"a tunnel leading south",
		tags16,
		tunnel2,
		tunnel1,
		tunnel1,
		"The passage leads back toward the tunnel mouth.",
		"You see",
		"You head back toward the entrance.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 17 = northFromTunnel2 */
		condition17,
		"a tunnel leading north",
		tags17,
		tunnel2,
		tunnel3,
		tunnel3,
		"With Sting's light, the way north becomes clear.",
		"You see",
		"You follow Sting's light deeper into the tunnel.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 18 = northFromTunnel2Blocked */
		condition18,
		"a tunnel leading north",
		tags18,
		tunnel2,
		NULL,
		tunnel3,
		"The darkness ahead is absolute.",
		"You see",
		"Without Sting's light, the black tunnel ahead is impassable.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 19 = southFromTunnel3 */
		alwaysTrue,
		"a tunnel leading south",
		tags19,
		tunnel3,
		tunnel2,
		tunnel2,
		"The way south leads back through the darkness.",
		"You see",
		"You make your way south.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 20 = northFromTunnel3 */
		condition20,
		"a tunnel sloping north",
		tags20,
		tunnel3,
		laketunnel,
		laketunnel,
		"Sting's light catches damp walls sloping toward the sound of water.",
		"You see",
		"You move toward the sound of water.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 21 = northFromTunnel3Blocked */
		condition21,
		"a tunnel sloping north",
		tags21,
		tunnel3,
		NULL,
		laketunnel,
		"The way ahead vanishes into blackness.",
		"You see",
		"Without light, you dare not go farther.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 22 = southFromLakeTunnel */
		alwaysTrue,
		"a tunnel leading south",
		tags22,
		laketunnel,
		tunnel3,
		tunnel3,
		"The tunnel rises back toward the upper passages.",
		"You see",
		"You head back up the tunnel.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 23 = northFromLakeTunnel */
		condition23,
		"a tunnel opening onto a lake",
		tags23,
		laketunnel,
		undergroundLake,
		undergroundLake,
		"Ahead, Sting's glow is swallowed by a vast dark lake.",
		"You see",
		"You step out beside the underground lake.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 24 = northFromLakeTunnelBlocked */
		condition24,
		"a tunnel opening onto a lake",
		tags24,
		laketunnel,
		NULL,
		undergroundLake,
		"The tunnel opens into a larger darkness.",
		"You see",
		"Without Sting, the way ahead is too dark to trust.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 25 = southFromLake */
		alwaysTrue,
		"the tunnel back south",
		tags25,
		undergroundLake,
		laketunnel,
		laketunnel,
		"The tunnel back south climbs away from the lake.",
		"You see",
		"You leave the lake behind.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 26 = eastFromLake */
		alwaysTrue,
		"a way onto the island",
		tags26,
		undergroundLake,
		gollumsisland,
		gollumsisland,
		"A slick path of stone leads onto the island.",
		"You see",
		"You step carefully onto the island.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 27 = westFromIsland */
		alwaysTrue,
		"the lake shore to the west",
		tags27,
		gollumsisland,
		undergroundLake,
		undergroundLake,
		"The way back leads over wet stone to the lakeside.",
		"You see",
		"You leave the island.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 28 = eastFromIsland */
		alwaysTrue,
		"the polished riddle rock",
		tags28,
		gollumsisland,
		riddlerock,
		riddlerock,
		"A smooth stone lies farther east, worn by use.",
		"You see",
		"You step onto the polished riddle rock.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 29 = westFromRock */
		condition29,
		"the way back to the island",
		tags29,
		riddlerock,
		gollumsisland,
		gollumsisland,
		"The island lies back to the west.",
		"You see",
		"You step back from the riddle rock.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 30 = westFromRockBlocked */
		condition30,
		"the way back to the island",
		tags30,
		riddlerock,
		NULL,
		gollumsisland,
		"Gollum watches every move from the edge of the rock.",
		"You see",
		"Gollum bars your way. You will not leave until the riddle game is finished.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 31 = eastToEscape */
		condition31,
		"the escape tunnel to the east",
		tags31,
		riddlerock,
		escapetunnel,
		escapetunnel,
		"Now that the game is won, the way out lies open.",
		"You see",
		"You slip into the escape tunnel.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 32 = eastToEscapeBlocked */
		condition32,
		"the escape tunnel to the east",
		tags32,
		riddlerock,
		NULL,
		escapetunnel,
		"The way out is here, but not yet yours.",
		"You see",
		"You cannot take the escape tunnel until the riddle game is complete.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 33 = openDoorToBackroom */
		alwaysTrue,
		"an unused door",
		tags33,
		NULL,
		NULL,
		NULL,
		"Compatibility object not used in this story.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		toggleDoorToBackroom,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 34 = closedDoorToBackroom */
		alwaysTrue,
		"an unused door",
		tags34,
		NULL,
		NULL,
		NULL,
		"Compatibility object not used in this story.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		toggleDoorToBackroom,
		isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 35 = openDoorToCave */
		alwaysTrue,
		"an unused door",
		tags35,
		NULL,
		NULL,
		NULL,
		"Compatibility object not used in this story.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		isAlreadyOpen,
		toggleDoorToCave,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 36 = closedDoorToCave */
		alwaysTrue,
		"an unused door",
		tags36,
		NULL,
		NULL,
		NULL,
		"Compatibility object not used in this story.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		toggleDoorToCave,
		isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 37 = openBox */
		alwaysTrue,
		"an unused box",
		tags37,
		NULL,
		NULL,
		NULL,
		"Compatibility object not used in this story.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		5,
		10,
		0,
		0,
		isAlreadyOpen,
		toggleBox,
		isStillOpen,
		isAlreadyOpen
	},
	{	/* 38 = closedBox */
		alwaysTrue,
		"an unused box",
		tags38,
		NULL,
		NULL,
		NULL,
		"Compatibility object not used in this story.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		5,
		0,
		0,
		0,
		toggleBox,
		isAlreadyClosed,
		toggleBoxLock,
		isAlreadyUnlocked
	},
	{	/* 39 = lockedBox */
		alwaysTrue,
		"an unused box",
		tags39,
		NULL,
		NULL,
		NULL,
		"Compatibility object not used in this story.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		5,
		0,
		0,
		0,
		isStillLocked,
		isAlreadyClosed,
		isAlreadyLocked,
		toggleBoxLock
	},
	{	/* 40 = keyForBox */
		alwaysTrue,
		"an unused key",
		tags40,
		NULL,
		NULL,
		NULL,
		"Compatibility object not used in this story.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		1,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	}
};
